# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-23 00:08
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('head_pic_url', models.CharField(default=b'/static/img/default.jpg', max_length=250, verbose_name='\u5934\u56fe\u94fe\u63a5')),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('brief', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6458\u8981')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='\u6b63\u6587')),
                ('page_views', models.PositiveIntegerField(default=0, editable=False, verbose_name='\u9605\u8bfb\u91cf')),
            ],
            options={
                'ordering': ['-pub_time'],
            },
        ),
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_1', models.CharField(db_index=True, max_length=30, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_2', models.CharField(db_index=True, max_length=30, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('friend_url', models.CharField(default=b'http://', max_length=250, verbose_name='\u94fe\u63a5')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Friend_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=30, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('head_pic_url', models.CharField(blank=True, default=b'/static/img/default.jpg', max_length=250, null=True, verbose_name='\u5934\u56fe\u94fe\u63a5')),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='\u6b63\u6587')),
            ],
            options={
                'ordering': ['-pub_time'],
            },
        ),
        migrations.CreateModel(
            name='Profile_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=30, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=30, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hill1895.Profile_Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='friend',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hill1895.Friend_Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hill1895.Category1', verbose_name='\u4e00\u7ea7\u76ee\u5f55'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hill1895.Category2', verbose_name='\u4e8c\u7ea7\u76ee\u5f55'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hill1895.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
