# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-07 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hill1895', '0004_auto_20180307_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dopusers',
            name='headpath',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dopusers',
            name='nichname',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dopusers',
            name='wxid',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
    ]
