# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-12 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hill1895', '0005_auto_20180307_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='dopusers',
            name='inuse',
            field=models.IntegerField(default=1),
        ),
    ]
