# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-17 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hill1895', '0007_dopusers_simpleheadpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='dopusers',
            name='thumb',
            field=models.BooleanField(default=False),
        ),
    ]
